name: Philo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compilation
      run: make -C philo
    
    - name: Testing make re
      run: make re -C philo

    - name: Norminette
      run: make norminette -C philo

    - name: Run philo-tester
      run: |
        wget -qO- https://raw.githubusercontent.com/Haletran/42_philosopher_tester/main/tester.sh > tester.sh
        chmod +x tester.sh
        ./tester.sh